name: Build
on:
  release:
    types:
      - published

env:
  DOCKER_BUILDKIT: 1
  DOCKER_PLATFORMS: linux/amd64,linux/arm64

jobs:
  get-next-tag:
    name: Get release tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: '0'
      - id: tag
        name: Get release tag
        run: |
          echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          
  build-binaries:
    name: Build binaries
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: 1.24.2
      - run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 go build -o ./bin/hue2govee-${{ matrix.goos }}-${{ matrix.goarch }} github.com/cedrickring/hue-to-govee/cmd/hue2govee
      - if: matrix.goos == 'windows'
        run: |
          mv ./bin/hue2govee-${{ matrix.goos }}-${{ matrix.goarch }} ./bin/hue2govee-${{ matrix.goos }}-${{ matrix.goarch }}.exe
      - uses: actions/upload-artifact@v4
        with:
          path: ./bin/hue2govee-*
          name: hue2govee-${{ matrix.goos }}-${{ matrix.goarch }}
      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: ./bin/hue2govee-*

  upload-binaries:
    name: Upload binaries
    runs-on: ubuntu-latest
    needs: build-binaries
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v4
        with:
          pattern: hue2govee-*
          merge-multiple: true
          path: binaries
      - name: Upload binaries to release
        run: |
          gh release upload ${{ github.event.release.tag_name }} ./binaries/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-publish-docker-image:
    needs: get-next-tag
    name: Build and publish images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/cedrickring/hue-to-govee
          tags: |
            ${{ needs.get-next-tag.outputs.tag }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: ${{ env.DOCKER_PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ghcr.io/cedrickring/hue-to-govee
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
